Crypto
mgrobertso/crypto-api pull request #1
Opened 2022-09-27 15:48 UTC by mgrobertso

Removed the template weather API.
 Added a controller for crypto along with Entity Framework and SqlExpress.
 Currently It does the basic CRUD operations 
<figure>
<img src=https://user-images.githubusercontent.com/109672728/192569779-1190b4a9-14ab-42cc-92aa-83744761b53f.PNG>
</figure>

My next plan Is to map out what my angular app needs, and connect it to my API instead of coin gecko.'
My plan is to have my API pull data form coin gecko and store It In a Database. Then Retrieve it with my API and Update as needed

2022-09-30 18:26 UTC, swhook52 requested changes

2022-09-30 18:26 UTC, swhook52 commented on crypto-api/Controllers/AuthController.cs
> +            return Ok(user);
We wouldn't really want to share the user's password even if it is hashed and definitely not the salt. We really just want to send back the user information that they care about. This does not include password stuff. I realize we're in a different situation because we don't really have auth but we still shouldn't need to send all that info back to the users.

Later we'll talk through DTOs and I have examples I can share.

2022-09-30 18:26 UTC, swhook52 commented on crypto-api/Controllers/CryptoController.cs
> +            return Ok(await _context.Cryptos.ToListAsync());
returning a "Created" response is more common with a POST. Then you would return the crypto that was created, not the full list of cryptos.

2022-09-30 18:26 UTC, swhook52 commented on crypto-api/Controllers/CryptoController.cs
> +            return Ok(await _context.Cryptos.ToListAsync());
Same thing here, you should return an OK with the crypto that you updated, not the full list.

2022-09-30 18:26 UTC, swhook52 commented on crypto-api/Controllers/CryptoController.cs
> +        private readonly DataContext _context;
You want to keep your DataContext out of the controller. Your controller should only really be concerned with calling into a service and return the proper http status code/message.

Create a Service layer where you can put things like your data context calls, saving, mapping and any business logic you might have. You can refer to an old repo I have that separates out some layers. https://github.com/swhook52/dotnetcore-blog

2022-09-30 18:26 UTC, swhook52 commented on crypto-api/Controllers/CryptoController.cs
> +            return Ok(await _context.Cryptos.ToListAsync());
Delete typically returns a 204 No Content because you did the task but don't have anything to return.

2022-09-30 18:26 UTC, swhook52 commented on crypto-api/Program.cs
> +builder.Services.AddControllers().AddNewtonsoftJson();
While it's ok to use Newtonsoft, there are many performance benefits to using the now built in System.Text.Json namespace for serialization and deserialization.
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-6-0

If you don't have a specific use for Newtonsoft, you should try not to add it.

2022-10-03 17:21 UTC, mgrobertso commented on crypto-api/Controllers/CryptoController.cs
> +            return Ok(await _context.Cryptos.ToListAsync());
```return Ok( dbcrypto);```

2022-10-07 20:34 UTC, closed without merging