Auth
mgrobertso/crypto-api pull request #2
Opened 2022-10-13 18:17 UTC by mgrobertso

2022-10-14 13:58 UTC, swhook52 requested changes

2022-10-14 13:58 UTC, swhook52 commented on crypto-api/Controllers/CryptoController.cs
> +        private readonly DataContext _context;
Same feedback here and probably other controllers... You want to move your datacontext to a service and simplify the controller. Right now all the business logic and data access and response logic is in one place. You need more separation of concerns which will allow for more testability when we get to unit testing.

2022-10-14 15:39 UTC, mgrobertso commented on crypto-api/Controllers/AuthController.cs
> +            return Ok("User has been Created");
```
            return Ok(new RegisterResponse
            {
                Id = user.Id,
                Firstname = user.FirstName,
                Lastname = user.LastName,
                Username = user.UserName,
                Email = user.Email
            });
```

2022-10-20 14:12 UTC, irwinhurstCEI commented on Crypto.Core/Repository/GenericRepository.cs
> +﻿using Crypto.Data;
Move any methods you need to your Service and delete this.

2022-10-20 14:13 UTC, irwinhurstCEI commented on Crypto.Core/Repository/IUnitOfWork.cs
> +﻿using Crypto.Core.DTOs;
DBContext is already a Unit Of Work so you dont need this abstraction,  Your Controllers should use your Services
https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext?view=entity-framework-6.2.0

2022-10-20 14:14 UTC, irwinhurstCEI commented on crypto-api/Controllers/AuthController.cs
> +﻿using AutoMapper;
REplace the UnitOfWork with a reference to your IAuthService

2022-10-20 14:16 UTC, irwinhurstCEI commented on Crypto.Core/Services/AuthService.cs
> +            return user;
Your services should return DTO objects.

2022-10-20 14:17 UTC, irwinhurstCEI commented on Crypto.Core/Services/ICryptoService.cs
> +﻿namespace Crypto.Core.Services
I think you are missing GetCryptoAsync() in your interface

2022-10-20 16:01 UTC, swhook52 reviewed
I see Irwin commented on some of the same things. just adding my notes as well.

2022-10-28 13:50 UTC, swhook52 approved these changes

2022-10-28 13:50 UTC, merged